# Generated by Django 2.2 on 2020-03-19 09:16

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Album',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(help_text='album title', max_length=100)),
                ('artist', models.CharField(help_text='album artist', max_length=100)),
                ('genre', models.CharField(help_text='album genre', max_length=50)),
                ('year', models.DateField(help_text='album year')),
            ],
        ),
    ]
